### PR TITLE
Add hourly updates

### PR DESCRIPTION
**Pull request by JoshHalvorson**
Hello! Started using this mod on a 24/7 server with fika and thought it'd be cool to have hourly updates like the Live Flea Prices mod. This is my first time working on a tarkov mod but am a little familiar with typescript so I thought id give it a go. Been running it for a few days now and it seems like its all working as expected 🤞 

This also removes the Therapist coefficient, mostly a personal choice as I wanted it to follow the data from tarkov.dev (I was seeing 1.3 mil when tarkov.dev said ~800k)

Feel free to not merge this, figured id share it just in case!

### CODE REVIEW

**Comment by SquareMan** [comment]
Thanks for the PR! This is a feature I've wanted to add for a while but haven't given myself the time to do it yet. I'll have to properly review this tomorrow but off the bat I'd probably want to see the coefficient removal reversed. I'll have to investigate what you said but you might have misinterpreted something. The value exists because the traders pay a percentage of the handbook value, but tarkov.dev just gives the trader value directly. This means we have to increase the retrieved price accordingly or the traders will end up paying less than in live. The console log prints the handbook value though which can be confusing. I would like to make the value configurable or something though because there are some minor issues with it currently.

It looks like your formatting might be a bit different. I don't really have anything set up for this in the project since I was just quickly uploading the code so I can probably just run my prettier config on it before merging.

**Comment by JoshHalvorson** [comment]
Oh interesting, I didnt know that! I'll revert that and the formatting to make it a little easier 😄 

Thanks for the info!

Edit: Installed prettier but the formatting didnt change, left it as is for now!

**Comment by SquareMan** [comment]
I misinterpreted the diff last night as replacing having some incorrect spacing but actually it was just because the code was moved into if/else block. Testing this now.

**Comment by SquareMan** [comment]
LGTM, gonna implement some more config options regarding the therapist coefficient myself before making a new release.

**Comment by JoshHalvorson** [comment]
Sweet, thank you!

**Pull request merged**
